version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: joi-creditcard-extension
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: joi-creditcard-extension-{{ epoch }}
          paths:
            - ~/.yarn-cache
            - node_modules
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: joi-creditcard-extension
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
